version: 2
jobs:
  deploy-master:
    docker:
      - image: circleci/python:3.6.1
    working_directory: ~/django-demo
    steps:
      - add_ssh_keys:
          fingerprints:
            - "12:98:83:66:db:34:d7:ee:62:39:d7:df:af:27:04:64"
      - checkout
      - run:
          name: Archive content of git repo without git files
          command: git archive -o django-demo.zip --format=zip HEAD
      - run:
          name: Create django-demo folder
          command: mkdir django-demo
      - run:
          name: Unzip django-demo
          command: cd django-demo && unzip ../django-demo.zip
      - run:
          name: Remove unimportant stuff
          command: cd django-demo && rm -rf .circleci
      - run:
          name: Deploy to EC2
          command: scp -o "StrictHostKeyChecking no" -r django-demo ubuntu@3.86.205.178:~/django-demo

workflows:
  version: 2
  build:
    jobs:
      - deploy-master:
          filters:
            branches:
              only: master



