version: 2
jobs:
  deploy-master:
    docker:
      - image: circleci/python:3.6.1
    working_directory: ~/django-demo
    steps:
      - add_ssh_keys:
          fingerprints:
            - "6e:9c:bf:ba:7e:89:59:19:d7:0d:23:bf:43:aa:ee:fc"
      - checkout
      - run:
          name: Archive content of git repo without git files
          command: git archive -o django-demo.zip --format=zip HEAD
      - run:
          name: Create django-demo folder
          command: mkdir django-demo
      - run:
          name: Unzip django-demo
          command: cd django-demo && unzip ../django-demo.zip
      - run:
          name: Remove unimportant stuff
          command: cd django-demo && rm -rf .circleci && rm .gitignore && rm -rf .vscode
      - run:
          name: Deploy to EC2
          command: scp -o "StrictHostKeyChecking no" -r django-demo ubuntu@ip-172-31-88-122:~/django-demo

workflows:
  version: 2
  build:
    jobs:
      - deploy-master:
          filters:
            branches:
              only: master



